"""empty message

Revision ID: 7fa53b839df4
Revises: ab709cb63bf1
Create Date: 2025-04-29 21:14:07.462469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7fa53b839df4'
down_revision = 'ab709cb63bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_metadata', sa.JSON(), nullable=True))
        batch_op.drop_column('additionl_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additionl_metadata', sqlite.JSON(), nullable=True))
        batch_op.drop_column('additional_metadata')

    # ### end Alembic commands ###
