"""Added file_url and metadata to ImageUpload, weather_data and cached_at to Destination

Revision ID: ab709cb63bf1
Revises: 8c9f746c27e6
Create Date: 2025-04-29 16:39:52.532205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab709cb63bf1'
down_revision = '8c9f746c27e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cached_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('image_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additionl_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_uploads', schema=None) as batch_op:
        batch_op.drop_column('additionl_metadata')
        batch_op.drop_column('file_url')

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('cached_at')
        batch_op.drop_column('weather_data')

    # ### end Alembic commands ###
